### ISSUE TITLE
10/31 Build Target Not Moving 

### ISSUE THREAD

**Issue by nlanter95** [mtu-most/franklin#25]
When I type in values or use the arrow keys on the target boxes under position the print location stays the same and does not move. Changing the angle still works.

**Comment by wijnen** [comment]
This works for me, I don't remember if I fixed anything for this.  Can you confirm whether this is still a problem for you?

**Comment by wijnen** [comment]
I did reproduce this problem, I think.  It has been fixed in the latest version on github.
