### ISSUE TITLE
Heated Bed option doesn't work

### ISSUE THREAD

**Issue by lmbrueck** [mtu-most/franklin#29]
In Franklin the Heated bed option doesn't seem to work on either the stable build (6-04-2016) or the latest build (2-16-2017). In the latest build you are unable to even check the box which says bed next to the temp settings. In all cases franklin treats the second temperature as a second extruder.

**Comment by wijnen** [comment]
Yes, extruders are not affected by this setting.  It only controls which
temperature is changed in response to M140 and M190 commands.

I'll have a look at the problem.

Thanks,
Bas

**Comment by lmbrueck** [comment]
Awesome. thanks Bas.
I would think that checking the "Bed' option should cause that temperature to be controlled by M140 and M190 commands and not be affected by any M104 and M109 commands.

**Comment by wijnen** [comment]
They are not coupled.  The bed checkbox means that this temperature is controlled with M140 and M190.  The extruders are always the first temperatures.  If you set one of the extruders to be the bed, it will be controlled by both methods.

The inability to check the box has been fixed, so I'm closing this issue.
