### ISSUE TITLE
Randomly on homing: #calling avr_sent_fragment with zero sending_fragment

### ISSUE THREAD

**Issue by gcanzalo** [mtu-most/franklin#48]
Resulting in freezing requiring a restart.

**Comment by wijnen** [comment]
I see the error message, but not the freeze. Can you check if it still happens now that #47 is fixed?

**Comment by gcanzalo** [comment]
Confirm that the message is displayed without freezing in the latest push.

**Comment by wijnen** [comment]
Good. I'm not sure if it's still a bug then. I'll downgrade it to minor so I may look at it when the important stuff is done.

**Comment by wijnen** [comment]
Haven't looked at this, but it doesn't seem to be a problem, so I'm closing this to clean up the issues list. Please open a new issue if there is a problem.
