### ISSUE TITLE
Franklin hangs when starting job

### ISSUE THREAD

**Issue by gcanzalo** [mtu-most/franklin#49]
Fri Jun  7 08:07:49 2019 EDT -0400: sending machine '74c5dedf-7a50-cb44-a7b2-f116c924c2fc'
$77:Invalid command i.
$77:Invalid command �.
$77:Invalid command �.
Fri Jun  7 08:08:12 2019 EDT -0400: running /home/debian/.cache/spool/franklin/74c5dedf-7a50-cb44-a7b2-f116c924c2fc/gcode/extruder_axel_x36.bin 0.000000 1.000000

**Comment by wijnen** [comment]
Does this happen for any job, or just sometimes? If not always, when does it happen?
What hardware is this on? Is it possible that some other program is trying to use the serial port?

**Comment by gcanzalo** [comment]
Occurs when multiple M104 commands are called. A single M104 works fine, more causes failure with no error messages.

**Comment by wijnen** [comment]
This error also randomly happens when starting a job with just a single M109 at the start. This means it hangs Franklin regularly, making it quite severe.
